[package]
name = "system_api"
authors = ["Confused Engineer"]
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
tokio = { version = "1.36.0", features = ["rt-multi-thread", "net"] }

[profile.release]
lto = "fat"
strip = "symbols"
codegen-units = 1